version: "3"

networks:
  apz:
    driver: bridge

services:
  facade1:
    build:
      context: ./FacadeService
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - apz
    environment:
      - SERVICE_ID=1
  logging-service1:
    build:
      context: ./LoggingService
      dockerfile: Dockerfile
    networks:
      - apz
    environment:
      - SERVICE_ID=1
  logging-service2:
    build:
      context: ./LoggingService
      dockerfile: Dockerfile
    networks:
      - apz
    environment:
      - SERVICE_ID=2
  logging-service3:
    build:
      context: ./LoggingService
      dockerfile: Dockerfile
    networks:
      - apz
    environment:
      - SERVICE_ID=3
  messages-service1:
    build:
      context: ./MessagesService
      dockerfile: Dockerfile
    networks:
      - apz
    environment:
      - SERVICE_ID=1
  messages-service2:
    build:
      context: ./MessagesService
      dockerfile: Dockerfile
    networks:
      - apz
    environment:
      - SERVICE_ID=2
  hazelcast1:
    image: hazelcast/hazelcast
    networks:
      - apz
  hazelcast2:
    image: hazelcast/hazelcast
    networks:
      - apz
  hazelcast3:
    image: hazelcast/hazelcast
    networks:
      - apz
  mc:
    image: hazelcast/management-center
    networks:
      - apz
    ports:
      - "8081:8080"

  consul:
    build:
      context: ./Consul
      dockerfile: Dockerfile
    networks:
      - apz
    ports:
      - "8500:8500"
      - "8600:8600/udp"
      - "8600:8600/tcp"
    volumes:
      - ./Consul/server1.json:/consul/config/server1.json:ro
    command: "agent -bootstrap-expect=1"